/**
 * QuestionsStep - Clarifying questions UI before council discussion
 *
 * Shows questions generated by the analyzer and collects user answers.
 * Continue button is disabled until all answers are non-empty.
 */

"use client";

import { useState, useCallback } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Loader2 } from "lucide-react";

interface QuestionsStepProps {
  questions: string[];
  onContinue: (answers: Record<string, string>) => Promise<void>;
  isSubmitting?: boolean;
}

export function QuestionsStep({
  questions,
  onContinue,
  isSubmitting = false,
}: QuestionsStepProps) {
  const [answers, setAnswers] = useState<Record<string, string>>(() =>
    questions.reduce((acc, _, idx) => ({ ...acc, [idx]: "" }), {})
  );

  const handleAnswerChange = useCallback((index: number, value: string) => {
    setAnswers((prev) => ({ ...prev, [index]: value }));
  }, []);

  const allAnswersFilled = questions.every(
    (_, idx) => answers[idx]?.trim().length > 0
  );

  const handleContinue = useCallback(async () => {
    if (!allAnswersFilled) return;
    // Map index keys to question text keys for clarity in stored data
    const answersMap: Record<string, string> = {};
    questions.forEach((q, idx) => {
      answersMap[q] = answers[idx];
    });
    await onContinue(answersMap);
  }, [allAnswersFilled, answers, questions, onContinue]);

  return (
    <div
      className="space-y-6 rounded-lg border bg-card p-6"
      data-testid="planning-questions-step"
    >
      <div>
        <h3 className="text-lg font-semibold">Clarifying Questions</h3>
        <p className="text-sm text-muted-foreground">
          Please answer these questions to help us better understand your
          project idea.
        </p>
      </div>

      <div className="space-y-4">
        {questions.map((question, idx) => (
          <div key={idx} className="space-y-2">
            <Label
              htmlFor={`answer-${idx}`}
              data-testid={`planning-question-${idx}`}
            >
              {question}
            </Label>
            <Input
              id={`answer-${idx}`}
              data-testid={`planning-answer-${idx}`}
              value={answers[idx] || ""}
              onChange={(e) => handleAnswerChange(idx, e.target.value)}
              placeholder="Your answer..."
              disabled={isSubmitting}
            />
          </div>
        ))}
      </div>

      <Button
        onClick={handleContinue}
        disabled={!allAnswersFilled || isSubmitting}
        data-testid="planning-questions-continue"
      >
        {isSubmitting ? (
          <>
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            Continuing...
          </>
        ) : (
          "Continue"
        )}
      </Button>
    </div>
  );
}
